# Site settings
title: "@defarbs - Home"
description: "Farbs' Official Site!"
baseurl: "" 
url: ""
# User settings
username: farbs
user_title: farbs - Penetration Tester
email: drewefarber@gmail.com
twitter_username: auxFarbs
github_username:  defarbs

# Build settings
markdown: kramdown
highlighter: rouge
permalink: /:title/

# html minify
compress_html:
  clippings: all
  comments: all
  endings: []
  profile: false

# Links to include in menu navigation
links:
  section_1:
    - title: home
      url: /
      key_trigger: 1
    - title: about me
      url: /about
      key_trigger: 2
    - title: my posts
      url: /posts
      key_trigger: 3
    - title: tags
      url: /tags
      key_trigger: 4
  section_2:
    - title: github
      url: https://www.github.com/defarbs
      new_tab: true
      key_trigger: g
    - title: twitter
      new_tab: true
      url: https://www.twitter.com/auxFarbs
      key_trigger: t
    - title: hackthebox
      new_tab: true
      url: https://www.hackthebox.eu/profile/39047
      key_trigger: h
    - title: search
      url: ""
      key_trigger: s #WARNING: search only works with "s"

# exclude node related stuff
exclude: ['package.json', 'src', 'node_modules']